repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs_replace
        args: ['--sort-by-required', '--dest=TERRAFORM.md']
      - id: terraform_validate
      - id: terraform_tflint
      - id: checkov
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.44.5  # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: infrastructure/*
